# monitor=*
# preload = ~/Pictures/wallpaper/shimada.jpg
# wallpaper = ,~/Pictures/wallpaper/shimada.jpg
preload = ~/Pictures/wallpaper/calm.jpg
wallpaper = ,~/Pictures/wallpaper/calm.jpg
# spash = true
# # ipc = true
# ipc = true

